### ISSUE TITLE
CLFB command should send two arguments, not three

### ISSUE THREAD

**Issue by luthere** [bitfocus/companion-module-rossvideo-xpression#2]
https://github.com/bitfocus/companion-module-rossvideo-xpression/blob/f33662797023f61885897893f2906d84df52554d/index.js#L70

The ui allows two arguments, but in the index.js, there is a third variable(takeID) that is undefined. I can see it wireshark as a undefined variable.

current: cmd = `CLFB ${opt.takeID}:${fb}:${opt.layer}`;
 fix: cmd = cmd = `CLFB ${fb}:${opt.layer}`;

**Comment by krocheck** [comment]
You are correct.  I double-checked all the actions and this was the only one that was off.  I added the two uncue actions as well that I either missed or are newer.

A build will be available in the Bitfocus website under the Beta Builds area with the updates.
