### ISSUE TITLE
Actions that reference a Layer can't select layers above 10

### ISSUE THREAD

**Issue by C47man** [bitfocus/companion-module-rossvideo-xpression#3]
The box for typing which layer your action applies to does not allow for values greater than 10 to be entered, forcing our Xpression operator to rebuild parts of our show for which we need companion macros. This appears to be the case for all Xpression actions which have a layer field. Similarly, we've had issues where the SEQO action doesn't work if the take item is on a layer higher than 10. This however appears to be intermittent, and I haven't figured out exactly what the conditions are to recreate it perfectly.

**Comment by krocheck** [comment]
Once upon a time the layers maxed at +/-10 ... has that changed to a higher number?

**Comment by C47man** [comment]
There is no limit to the number of layers that a framebuffer can use. I wasn't aware that there used to be a limit!

**Comment by C47man** [comment]
Any chance of getting this addressed?
